AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tp_lambda_dynamo

  Sample SAM Template for tp_lambda_dynamo
Globals:
  Function:
    Timeout: 3

Resources:
  GetFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.get_handler
      Runtime: nodejs14.x
      Events:
        GetRequest:
          Type: Api 
          Properties:
            Path: /envios/pendientes
            Method: get
  PutFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.put_handler
      Runtime: nodejs14.x
      Events:
        PutRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put
  PostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.post_handler
      Runtime: nodejs14.x
      Events:
        PostRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /envios
            Method: post
